import "./App.css"
import Navbar from "./components/Navbar"

function App() {
  return (
    <div className="App">
      <Navbar />
    </div>
  )
}

export default App

/*

Feature List:

1. -- Press Start to Continue --
    Have the "/" be a screen that just has ToolShed + Credits and at bottom it says "Press Any Key to Continue" blinking

2. Settings Pages for some tools
    The settings page would allow them to make changes to the output generated by setting a specific variable such as the name of a Whitelist from the Generic term used currently

3. Light Dark Mode
    Bool Logic that flips the color scheme of the app that can be adjust in settings

4. 


*/
